---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8-stretch

inputs:
  - name: dp-map-builder-ui

outputs:
  - name: build
  - name: package

run:
  path: dp-map-builder-ui/ci/scripts/build.sh
